---
# Create calico-namespace with label pod-security.kubernetes.io/enforce: privileged
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: create-calico-ns
spec:
  clusterSelector:
    matchLabels:
      network: calico-vxlan-v3-32-0
  policyRefs:
  - name: calico-namespace
    namespace: default
    kind: ConfigMap
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-calico
spec:
  dependsOn:
  - create-calico-ns
  syncMode: Continuous
  clusterSelector:
    matchLabels:
      network: calico-vxlan-v3-32-0
  helmCharts:
  - repositoryURL:    https://projectcalico.docs.tigera.io/charts
    repositoryName:   projectcalico
    chartName:        projectcalico/tigera-operator
    chartVersion:     v3.32.0
    releaseName:      calico
    releaseNamespace: tigera-operator
    helmChartAction:  Install
    values: |
      installation:
        calicoNetwork:
          ipPools:
          {{ range $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
            - cidr: {{ $cidr }}
              encapsulation: VXLAN
          {{ end }}