apiVersion: v1
data:
  calico-namespace.yaml: |-
    apiVersion: v1
    data:
      calico-ns.yaml: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: tigera-operator
          labels:
            name: tigera-operator
            pod-security.kubernetes.io/enforce: privileged
    kind: ConfigMap
    metadata:
      name: calico-namespace
      namespace: default
kind: ConfigMap
metadata:
  name: calico-namespace
  namespace: default
