apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
  KUBERNETES_SERVICE_PORT: "{{ .Cluster.spec.controlPlaneEndpoint.port }}"