apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sveltos-clusterprofiles
  namespace: flux2
spec:
  interval: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: awesome-projectsveltos-resources
  path: ./management/clusterprofiles