apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: calico-clusterprofile
spec:
  dependsOn: calico-clusterprofile-config
  clusterSelector:
    matchLabels:
      network: calico
  syncMode: Continuous

  helmCharts:
  - repositoryURL:    https://docs.tigera.io/calico/charts
    repositoryName:   projectcalico
    chartName:        projectcalico/tigera-operator
    chartVersion:     v3.32.1
    releaseName:      calico
    releaseNamespace: tigera-operator
    helmChartAction:  Install
