apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: calico-clusterprofile-config
spec:
  continueOnError: true
  clusterSelector:
    matchLabels:
      network: calico
  syncMode: ContinuousWithDriftDetection
  policyRefs:
  - kind: GitRepository
    name: awesome-projectsveltos-resources
    namespace: flux2
    path: ./networking/calico/configs/  

