---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: calico-crd-clusterprofile-vxlan-v3-32-0
spec:
  clusterSelector:
    matchLabels:
      network: calico-vxlan-v3-32-0
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL: https://projectcalico.docs.tigera.io/charts
    repositoryName: projectcalico
    chartName: crd.projectcalico.org.v1
    chartVersion: v3.32.0
    releaseName: calico-crd
    releaseNamespace: default
    helmChartAction: Install
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: calico-clusterprofile-vxlan-v3-32-0
spec:
  continueOnError: true
  dependsOn:
  - calico-crd-clusterprofile-vxlan-v3-32-0
  clusterSelector:
    matchLabels:
      network: calico-vxlan-v3-32-0
  syncMode: ContinuousWithDriftDetection
  policyRefs:
  - kind: GitRepository
    name: awesome-projectsveltos-resources
    namespace: flux2
    path: ./networking/calico-vxlan-v3.32.0/configs/
  helmCharts:
  - repositoryURL:    https://projectcalico.docs.tigera.io/charts
    repositoryName:   projectcalico
    chartName:        projectcalico/tigera-operator
    chartVersion:     v3.32.0
    releaseName:      calico
    releaseNamespace: tigera-operator
    helmChartAction:  Install
    values: |
      installation:
        calicoNetwork:
          ipPools:
          {{ range $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
            - cidr: {{ $cidr }}
              encapsulation: VXLAN
          {{ end }}
